deployments:
  simple-web-server-1:
    replicaCount: 1
    image:
      repository: nginx
      tag: latest
      pullPolicy: IfNotPresent
    service:
      type: ClusterIP
      port: 80
      targetPort: 8080
    homepage:
      title: "Welcome - Server 1"
      content: |
        <h1>Simple Web Server 1</h1>
        <p>This is the first web server deployed with Helm.</p>
  simple-web-server-2:
    replicaCount: 1
    image:
      repository: nginx
      tag: latest
      pullPolicy: IfNotPresent
    service:
      type: ClusterIP
      port: 81
      targetPort: 8080
    homepage:
      title: "Welcome - Server 2"
      content: |
        <h1>Simple Web Server 2</h1>
        <p>This is the second web server deployed with Helm.</p>
