{{- $config := include "simple-web-server.deploymentConfig" . | fromYaml }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "simple-web-server.fullname" . }}
  labels:
    {{- include "simple-web-server.labels" . | nindent 4 }}
spec:
  replicas: {{ $config.replicaCount }}
  selector:
    matchLabels:
      {{- include "simple-web-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "simple-web-server.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: webserver
        image: "{{ $config.image.repository }}:{{ $config.image.tag }}"
        imagePullPolicy: {{ $config.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        volumeMounts:
        - name: homepage
          mountPath: /usr/share/nginx/html
      volumes:
      - name: homepage
        configMap:
          name: {{ include "simple-web-server.fullname" . }}-homepage
